EBP-910 add user id query to fetch user id
Zbyteio/middleware-lib pull request #1
Opened 2022-07-27 04:09 UTC by sourabhmandal

2022-07-27 04:35 UTC, srivallabh-mangrulkar requested changes
We are using the verifyJwtToken method in every service, what is the rationale behind removing it?

2022-07-27 04:35 UTC, srivallabh-mangrulkar commented on jwt.go
> +		fmt.Print(err.Error())
Use log instead of fmt

2022-07-27 04:45 UTC, ravizbyte approved these changes

2022-07-27 11:24 UTC, sourabhmandal commented on jwt.go
> +		fmt.Print(err.Error())
okay

2022-07-27 11:56 UTC, sourabhmandal commented
> We are using the verifyJwtToken method in every service, what is the rationale behind removing it?

According to the discussion, all token verification issuing and refreshing will be done by the new auth service.
This middleware layer will later become the gateway layer and the middleware-lib will retire.

- To avoid rework later, less logic is implemented in the middleware layer.
- Push toward single responsibility, auth service should handle all JWT stuff

2022-07-27 11:59 UTC, anant-zbyte approved these changes

2022-07-27 17:18 UTC, ravizbyte approved these changes

2022-07-29 12:32 UTC, srivallabh-mangrulkar approved these changes

2022-07-29 12:35 UTC, merged